/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.VIEW;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {

     public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public MainForm(int userRoli) {
        initComponents();
        //Nese doni me bo max screen e shkruni kodin me poshte:
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        if(userRoli != 1){
            jButton1.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        navMenu = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        exitMI = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        copyMI = new javax.swing.JMenuItem();
        pasteMI = new javax.swing.JMenuItem();
        UshqimetMI = new javax.swing.JMenu();
        ushqimetMI = new javax.swing.JMenuItem();
        PorositeMI = new javax.swing.JMenuItem();
        TavolinaMI = new javax.swing.JMenuItem();
        OrariMI = new javax.swing.JMenuItem();
        VendiMI = new javax.swing.JMenuItem();
        PerdoruesitMI = new javax.swing.JMenuItem();

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Admin Options");

        jButton1.setText("Ushqimet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Porositë");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tavolina");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Orari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Vendi");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navMenuLayout = new javax.swing.GroupLayout(navMenu);
        navMenu.setLayout(navMenuLayout);
        navMenuLayout.setHorizontalGroup(
            navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMenuLayout.createSequentialGroup()
                .addGroup(navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navMenuLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1))
                    .addGroup(navMenuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2)
                        .addGap(58, 58, 58)
                        .addComponent(jButton3)
                        .addGap(57, 57, 57)
                        .addComponent(jButton4)
                        .addGap(55, 55, 55)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navMenuLayout.setVerticalGroup(
            navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        navMenu.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        navMenu.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        navMenu.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        navMenu.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        navMenu.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        navMenu.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        jMenu5.setText("File");

        exitMI.setText("exit");
        jMenu5.add(exitMI);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");

        copyMI.setText("Copy");
        copyMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMIActionPerformed(evt);
            }
        });
        jMenu6.add(copyMI);

        pasteMI.setText("Paste");
        jMenu6.add(pasteMI);

        jMenuBar2.add(jMenu6);

        UshqimetMI.setText("Admin Options");

        ushqimetMI.setText("Ushqimet");
        ushqimetMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ushqimetMIActionPerformed(evt);
            }
        });
        UshqimetMI.add(ushqimetMI);

        PorositeMI.setText("Porosite");
        PorositeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorositeMIActionPerformed(evt);
            }
        });
        UshqimetMI.add(PorositeMI);

        TavolinaMI.setText("Tavolinat");
        TavolinaMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TavolinaMIActionPerformed(evt);
            }
        });
        UshqimetMI.add(TavolinaMI);

        OrariMI.setText("Orari");
        OrariMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrariMIActionPerformed(evt);
            }
        });
        UshqimetMI.add(OrariMI);

        VendiMI.setText("Vendi");
        VendiMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendiMIActionPerformed(evt);
            }
        });
        UshqimetMI.add(VendiMI);

        PerdoruesitMI.setText("Perdoruesit");
        UshqimetMI.add(PerdoruesitMI);

        jMenuBar2.add(UshqimetMI);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navMenu)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copyMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyMIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UshqimiForm uf = new UshqimiForm();
        desktopPane.add(uf);
        uf.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ushqimetMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ushqimetMIActionPerformed
        // TODO add your handling code here:
        UshqimiForm uf = new UshqimiForm();
        desktopPane.add(uf);
        uf.show();
    }//GEN-LAST:event_ushqimetMIActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PorosiaForm pf = new PorosiaForm();
        desktopPane.add(pf);
        pf.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TavolinaForm tf = new TavolinaForm();
        desktopPane.add(tf);
        tf.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        OrariForm of = new OrariForm();
        desktopPane.add(of);
        of.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        VendiForm vf = new VendiForm();
        desktopPane.add(vf);
        vf.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void PorositeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorositeMIActionPerformed
        // TODO add your handling code here:
        PorosiaForm pf = new PorosiaForm();
        desktopPane.add(pf);
        pf.show();
    }//GEN-LAST:event_PorositeMIActionPerformed

    private void TavolinaMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TavolinaMIActionPerformed
        // TODO add your handling code here:
        TavolinaForm tf = new TavolinaForm();
        desktopPane.add(tf);
        tf.show();
    }//GEN-LAST:event_TavolinaMIActionPerformed

    private void OrariMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrariMIActionPerformed
        // TODO add your handling code here:
        OrariForm of = new OrariForm();
        desktopPane.add(of);
        of.show();
    }//GEN-LAST:event_OrariMIActionPerformed

    private void VendiMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendiMIActionPerformed
        // TODO add your handling code here:
        VendiForm vf = new VendiForm();
        desktopPane.add(vf);
        vf.show();
    }//GEN-LAST:event_VendiMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OrariMI;
    private javax.swing.JMenuItem PerdoruesitMI;
    private javax.swing.JMenuItem PorositeMI;
    private javax.swing.JMenuItem TavolinaMI;
    private javax.swing.JMenu UshqimetMI;
    private javax.swing.JMenuItem VendiMI;
    private javax.swing.JMenuItem copyMI;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMI;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JDesktopPane navMenu;
    private javax.swing.JMenuItem pasteMI;
    private javax.swing.JMenuItem ushqimetMI;
    // End of variables declaration//GEN-END:variables
}
